<?php

use Illuminate\Database\Seeder;
use App\Models\Location;

class LocationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $locations = array(
            array('id' => '1','state_id' => '1','lga' => 'Aba North'),
            array('id' => '2','state_id' => '1','lga' => 'Aba South'),
            array('id' => '3','state_id' => '1','lga' => 'Arochukwu'),
            array('id' => '4','state_id' => '1','lga' => 'Bende'),
            array('id' => '5','state_id' => '1','lga' => 'Ikwuano'),
            array('id' => '6','state_id' => '1','lga' => 'Isiala Ngwa North'),
            array('id' => '7','state_id' => '1','lga' => 'Isiala Ngwa South'),
            array('id' => '8','state_id' => '1','lga' => 'Isuikwuato'),
            array('id' => '9','state_id' => '1','lga' => 'Obi Ngwa'),
            array('id' => '10','state_id' => '1','lga' => 'Ohafia'),
            array('id' => '11','state_id' => '1','lga' => 'Osisioma'),
            array('id' => '12','state_id' => '1','lga' => 'Ugwunagbo'),
            array('id' => '13','state_id' => '1','lga' => 'Ukwa East'),
            array('id' => '14','state_id' => '1','lga' => 'Ukwa West'),
            array('id' => '15','state_id' => '1','lga' => 'Umuahia North'),
            array('id' => '16','state_id' => '1','lga' => 'Umuahia South'),
            array('id' => '17','state_id' => '1','lga' => 'Umu Nneochi'),
            array('id' => '18','state_id' => '2','lga' => 'Demsa'),
            array('id' => '19','state_id' => '2','lga' => 'Fufure'),
            array('id' => '20','state_id' => '2','lga' => 'Ganye'),
            array('id' => '21','state_id' => '2','lga' => 'Gayuk'),
            array('id' => '22','state_id' => '2','lga' => 'Gombi'),
            array('id' => '23','state_id' => '2','lga' => 'Grie'),
            array('id' => '24','state_id' => '2','lga' => 'Hong'),
            array('id' => '25','state_id' => '2','lga' => 'Jada'),
            array('id' => '26','state_id' => '2','lga' => 'Larmurde'),
            array('id' => '27','state_id' => '2','lga' => 'Madagali'),
            array('id' => '28','state_id' => '2','lga' => 'Maiha'),
            array('id' => '29','state_id' => '2','lga' => 'Mayo Belwa'),
            array('id' => '30','state_id' => '2','lga' => 'Michika'),
            array('id' => '31','state_id' => '2','lga' => 'Mubi North'),
            array('id' => '32','state_id' => '2','lga' => 'Mubi South'),
            array('id' => '33','state_id' => '2','lga' => 'Numan'),
            array('id' => '34','state_id' => '2','lga' => 'Shelleng'),
            array('id' => '35','state_id' => '2','lga' => 'Song'),
            array('id' => '36','state_id' => '2','lga' => 'Toungo'),
            array('id' => '37','state_id' => '2','lga' => 'Yola North'),
            array('id' => '38','state_id' => '2','lga' => 'Yola South'),
            array('id' => '39','state_id' => '3','lga' => 'Abak'),
            array('id' => '40','state_id' => '3','lga' => 'Eastern Obolo'),
            array('id' => '41','state_id' => '3','lga' => 'Eket'),
            array('id' => '42','state_id' => '3','lga' => 'Esit Eket'),
            array('id' => '43','state_id' => '3','lga' => 'Essien Udim'),
            array('id' => '44','state_id' => '3','lga' => 'Etim Ekpo'),
            array('id' => '45','state_id' => '3','lga' => 'Etinan'),
            array('id' => '46','state_id' => '3','lga' => 'Ibeno'),
            array('id' => '47','state_id' => '3','lga' => 'Ibesikpo Asutan'),
            array('id' => '48','state_id' => '3','lga' => 'Ibiono-Ibom'),
            array('id' => '49','state_id' => '3','lga' => 'Ika'),
            array('id' => '50','state_id' => '3','lga' => 'Ikono'),
            array('id' => '51','state_id' => '3','lga' => 'Ikot Abasi'),
            array('id' => '52','state_id' => '3','lga' => 'Ikot Ekpene'),
            array('id' => '53','state_id' => '3','lga' => 'Ini'),
            array('id' => '54','state_id' => '3','lga' => 'Itu'),
            array('id' => '55','state_id' => '3','lga' => 'Mbo'),
            array('id' => '56','state_id' => '3','lga' => 'Mkpat-Enin'),
            array('id' => '57','state_id' => '3','lga' => 'Nsit-Atai'),
            array('id' => '58','state_id' => '3','lga' => 'Nsit-Ibom'),
            array('id' => '59','state_id' => '3','lga' => 'Nsit-Ubium'),
            array('id' => '60','state_id' => '3','lga' => 'Obot Akara'),
            array('id' => '61','state_id' => '3','lga' => 'Okobo'),
            array('id' => '62','state_id' => '3','lga' => 'Onna'),
            array('id' => '63','state_id' => '3','lga' => 'Oron'),
            array('id' => '64','state_id' => '3','lga' => 'Oruk Anam'),
            array('id' => '65','state_id' => '3','lga' => 'Udung-Uko'),
            array('id' => '66','state_id' => '3','lga' => 'Ukanafun'),
            array('id' => '67','state_id' => '3','lga' => 'Uruan'),
            array('id' => '68','state_id' => '3','lga' => 'Urue-Offong/Oruko'),
            array('id' => '69','state_id' => '3','lga' => 'Uyo'),
            array('id' => '70','state_id' => '4','lga' => 'Aguata'),
            array('id' => '71','state_id' => '4','lga' => 'Anambra East'),
            array('id' => '72','state_id' => '4','lga' => 'Anambra West'),
            array('id' => '73','state_id' => '4','lga' => 'Anaocha'),
            array('id' => '74','state_id' => '4','lga' => 'Awka North'),
            array('id' => '75','state_id' => '4','lga' => 'Awka South'),
            array('id' => '76','state_id' => '4','lga' => 'Ayamelum'),
            array('id' => '77','state_id' => '4','lga' => 'Dunukofia'),
            array('id' => '78','state_id' => '4','lga' => 'Ekwusigo'),
            array('id' => '79','state_id' => '4','lga' => 'Idemili North'),
            array('id' => '80','state_id' => '4','lga' => 'Idemili South'),
            array('id' => '81','state_id' => '4','lga' => 'Ihiala'),
            array('id' => '82','state_id' => '4','lga' => 'Njikoka'),
            array('id' => '83','state_id' => '4','lga' => 'Nnewi North'),
            array('id' => '84','state_id' => '4','lga' => 'Nnewi South'),
            array('id' => '85','state_id' => '4','lga' => 'Ogbaru'),
            array('id' => '86','state_id' => '4','lga' => 'Onitsha North'),
            array('id' => '87','state_id' => '4','lga' => 'Onitsha South'),
            array('id' => '88','state_id' => '4','lga' => 'Orumba North'),
            array('id' => '89','state_id' => '4','lga' => 'Orumba South'),
            array('id' => '90','state_id' => '4','lga' => 'Oyi'),
            array('id' => '91','state_id' => '5','lga' => 'Alkaleri'),
            array('id' => '92','state_id' => '5','lga' => 'Bauchi'),
            array('id' => '93','state_id' => '5','lga' => 'Bogoro'),
            array('id' => '94','state_id' => '5','lga' => 'Damban'),
            array('id' => '95','state_id' => '5','lga' => 'Darazo'),
            array('id' => '96','state_id' => '5','lga' => 'Dass'),
            array('id' => '97','state_id' => '5','lga' => 'Gamawa'),
            array('id' => '98','state_id' => '5','lga' => 'Ganjuwa'),
            array('id' => '99','state_id' => '5','lga' => 'Giade'),
            array('id' => '100','state_id' => '5','lga' => 'Itas/Gadau'),
            array('id' => '101','state_id' => '5','lga' => 'Jama\'are'),
            array('id' => '102','state_id' => '5','lga' => 'Katagum'),
            array('id' => '103','state_id' => '5','lga' => 'Kirfi'),
            array('id' => '104','state_id' => '5','lga' => 'Misau'),
            array('id' => '105','state_id' => '5','lga' => 'Ningi'),
            array('id' => '106','state_id' => '5','lga' => 'Shira'),
            array('id' => '107','state_id' => '5','lga' => 'Tafawa Balewa'),
            array('id' => '108','state_id' => '5','lga' => 'Toro'),
            array('id' => '109','state_id' => '5','lga' => 'Warji'),
            array('id' => '110','state_id' => '5','lga' => 'Zaki'),
            array('id' => '111','state_id' => '6','lga' => 'Brass'),
            array('id' => '112','state_id' => '6','lga' => 'Ekeremor'),
            array('id' => '113','state_id' => '6','lga' => 'Kolokuma/Opokuma'),
            array('id' => '114','state_id' => '6','lga' => 'Nembe'),
            array('id' => '115','state_id' => '6','lga' => 'Ogbia'),
            array('id' => '116','state_id' => '6','lga' => 'Sagbama'),
            array('id' => '117','state_id' => '6','lga' => 'Southern Ijaw'),
            array('id' => '118','state_id' => '6','lga' => 'Yenagoa'),
            array('id' => '119','state_id' => '7','lga' => 'Agatu'),
            array('id' => '120','state_id' => '7','lga' => 'Apa'),
            array('id' => '121','state_id' => '7','lga' => 'Ado'),
            array('id' => '122','state_id' => '7','lga' => 'Buruku'),
            array('id' => '123','state_id' => '7','lga' => 'Gboko'),
            array('id' => '124','state_id' => '7','lga' => 'Guma'),
            array('id' => '125','state_id' => '7','lga' => 'Gwer East'),
            array('id' => '126','state_id' => '7','lga' => 'Gwer West'),
            array('id' => '127','state_id' => '7','lga' => 'Katsina-Ala'),
            array('id' => '128','state_id' => '7','lga' => 'Konshisha'),
            array('id' => '129','state_id' => '7','lga' => 'Kwande'),
            array('id' => '130','state_id' => '7','lga' => 'Logo'),
            array('id' => '131','state_id' => '7','lga' => 'Makurdi'),
            array('id' => '132','state_id' => '7','lga' => 'Obi'),
            array('id' => '133','state_id' => '7','lga' => 'Ogbadibo'),
            array('id' => '134','state_id' => '7','lga' => 'Ohimini'),
            array('id' => '135','state_id' => '7','lga' => 'Oju'),
            array('id' => '136','state_id' => '7','lga' => 'Okpokwu'),
            array('id' => '137','state_id' => '7','lga' => 'Oturkpo'),
            array('id' => '138','state_id' => '7','lga' => 'Tarka'),
            array('id' => '139','state_id' => '7','lga' => 'Ukum'),
            array('id' => '140','state_id' => '7','lga' => 'Ushongo'),
            array('id' => '141','state_id' => '7','lga' => 'Vandeikya'),
            array('id' => '142','state_id' => '8','lga' => 'Abadam'),
            array('id' => '143','state_id' => '8','lga' => 'Askira/Uba'),
            array('id' => '144','state_id' => '8','lga' => 'Bama'),
            array('id' => '145','state_id' => '8','lga' => 'Bayo'),
            array('id' => '146','state_id' => '8','lga' => 'Biu'),
            array('id' => '147','state_id' => '8','lga' => 'Chibok'),
            array('id' => '148','state_id' => '8','lga' => 'Damboa'),
            array('id' => '149','state_id' => '8','lga' => 'Dikwa'),
            array('id' => '150','state_id' => '8','lga' => 'Gubio'),
            array('id' => '151','state_id' => '8','lga' => 'Guzamala'),
            array('id' => '152','state_id' => '8','lga' => 'Gwoza'),
            array('id' => '153','state_id' => '8','lga' => 'Hawul'),
            array('id' => '154','state_id' => '8','lga' => 'Jere'),
            array('id' => '155','state_id' => '8','lga' => 'Kaga'),
            array('id' => '156','state_id' => '8','lga' => 'Kala/Balge'),
            array('id' => '157','state_id' => '8','lga' => 'Konduga'),
            array('id' => '158','state_id' => '8','lga' => 'Kukawa'),
            array('id' => '159','state_id' => '8','lga' => 'Kwaya Kusar'),
            array('id' => '160','state_id' => '8','lga' => 'Mafa'),
            array('id' => '161','state_id' => '8','lga' => 'Magumeri'),
            array('id' => '162','state_id' => '8','lga' => 'Maiduguri'),
            array('id' => '163','state_id' => '8','lga' => 'Marte'),
            array('id' => '164','state_id' => '8','lga' => 'Mobbar'),
            array('id' => '165','state_id' => '8','lga' => 'Monguno'),
            array('id' => '166','state_id' => '8','lga' => 'Ngala'),
            array('id' => '167','state_id' => '8','lga' => 'Nganzai'),
            array('id' => '168','state_id' => '8','lga' => 'Shani'),
            array('id' => '169','state_id' => '9','lga' => 'Abi'),
            array('id' => '170','state_id' => '9','lga' => 'Akamkpa'),
            array('id' => '171','state_id' => '9','lga' => 'Akpabuyo'),
            array('id' => '172','state_id' => '9','lga' => 'Bakassi'),
            array('id' => '173','state_id' => '9','lga' => 'Bekwarra'),
            array('id' => '174','state_id' => '9','lga' => 'Biase'),
            array('id' => '175','state_id' => '9','lga' => 'Boki'),
            array('id' => '176','state_id' => '9','lga' => 'Calabar Municipal'),
            array('id' => '177','state_id' => '9','lga' => 'Calabar South'),
            array('id' => '178','state_id' => '9','lga' => 'Etung'),
            array('id' => '179','state_id' => '9','lga' => 'Ikom'),
            array('id' => '180','state_id' => '9','lga' => 'Obanliku'),
            array('id' => '181','state_id' => '9','lga' => 'Obubra'),
            array('id' => '182','state_id' => '9','lga' => 'Obudu'),
            array('id' => '183','state_id' => '9','lga' => 'Odukpani'),
            array('id' => '184','state_id' => '9','lga' => 'Ogoja'),
            array('id' => '185','state_id' => '9','lga' => 'Yakuur'),
            array('id' => '186','state_id' => '9','lga' => 'Yala'),
            array('id' => '187','state_id' => '10','lga' => 'Aniocha North'),
            array('id' => '188','state_id' => '10','lga' => 'Aniocha South'),
            array('id' => '189','state_id' => '10','lga' => 'Bomadi'),
            array('id' => '190','state_id' => '10','lga' => 'Burutu'),
            array('id' => '191','state_id' => '10','lga' => 'Ethiope East'),
            array('id' => '192','state_id' => '10','lga' => 'Ethiope West'),
            array('id' => '193','state_id' => '10','lga' => 'Ika North East'),
            array('id' => '194','state_id' => '10','lga' => 'Ika South'),
            array('id' => '195','state_id' => '10','lga' => 'Isoko North'),
            array('id' => '196','state_id' => '10','lga' => 'Isoko South'),
            array('id' => '197','state_id' => '10','lga' => 'Ndokwa East'),
            array('id' => '198','state_id' => '10','lga' => 'Ndokwa West'),
            array('id' => '199','state_id' => '10','lga' => 'Okpe'),
            array('id' => '200','state_id' => '10','lga' => 'Oshimili North'),
            array('id' => '201','state_id' => '10','lga' => 'Oshimili South'),
            array('id' => '202','state_id' => '10','lga' => 'Patani'),
            array('id' => '203','state_id' => '10','lga' => 'Sapele, Delta'),
            array('id' => '204','state_id' => '10','lga' => 'Udu'),
            array('id' => '205','state_id' => '10','lga' => 'Ughelli North'),
            array('id' => '206','state_id' => '10','lga' => 'Ughelli South'),
            array('id' => '207','state_id' => '10','lga' => 'Ukwuani'),
            array('id' => '208','state_id' => '10','lga' => 'Uvwie'),
            array('id' => '209','state_id' => '10','lga' => 'Warri North'),
            array('id' => '210','state_id' => '10','lga' => 'Warri South'),
            array('id' => '211','state_id' => '10','lga' => 'Warri South West'),
            array('id' => '212','state_id' => '11','lga' => 'Abakaliki'),
            array('id' => '213','state_id' => '11','lga' => 'Afikpo North'),
            array('id' => '214','state_id' => '11','lga' => 'Afikpo South'),
            array('id' => '215','state_id' => '11','lga' => 'Ebonyi'),
            array('id' => '216','state_id' => '11','lga' => 'Ezza North'),
            array('id' => '217','state_id' => '11','lga' => 'Ezza South'),
            array('id' => '218','state_id' => '11','lga' => 'Ikwo'),
            array('id' => '219','state_id' => '11','lga' => 'Ishielu'),
            array('id' => '220','state_id' => '11','lga' => 'Ivo'),
            array('id' => '221','state_id' => '11','lga' => 'Izzi'),
            array('id' => '222','state_id' => '11','lga' => 'Ohaozara'),
            array('id' => '223','state_id' => '11','lga' => 'Ohaukwu'),
            array('id' => '224','state_id' => '11','lga' => 'Onicha'),
            array('id' => '225','state_id' => '12','lga' => 'Akoko-Edo'),
            array('id' => '226','state_id' => '12','lga' => 'Egor'),
            array('id' => '227','state_id' => '12','lga' => 'Esan Central'),
            array('id' => '228','state_id' => '12','lga' => 'Esan North-East'),
            array('id' => '229','state_id' => '12','lga' => 'Esan South-East'),
            array('id' => '230','state_id' => '12','lga' => 'Esan West'),
            array('id' => '231','state_id' => '12','lga' => 'Etsako Central'),
            array('id' => '232','state_id' => '12','lga' => 'Etsako East'),
            array('id' => '233','state_id' => '12','lga' => 'Etsako West'),
            array('id' => '234','state_id' => '12','lga' => 'Igueben'),
            array('id' => '235','state_id' => '12','lga' => 'Ikpoba Okha'),
            array('id' => '236','state_id' => '12','lga' => 'Orhionmwon'),
            array('id' => '237','state_id' => '12','lga' => 'Oredo'),
            array('id' => '238','state_id' => '12','lga' => 'Ovia North-East'),
            array('id' => '239','state_id' => '12','lga' => 'Ovia South-West'),
            array('id' => '240','state_id' => '12','lga' => 'Owan East'),
            array('id' => '241','state_id' => '12','lga' => 'Owan West'),
            array('id' => '242','state_id' => '12','lga' => 'Uhunmwonde'),
            array('id' => '243','state_id' => '13','lga' => 'Ado Ekiti'),
            array('id' => '244','state_id' => '13','lga' => 'Efon'),
            array('id' => '245','state_id' => '13','lga' => 'Ekiti East'),
            array('id' => '246','state_id' => '13','lga' => 'Ekiti South-West'),
            array('id' => '247','state_id' => '13','lga' => 'Ekiti West'),
            array('id' => '248','state_id' => '13','lga' => 'Emure'),
            array('id' => '249','state_id' => '13','lga' => 'Gbonyin'),
            array('id' => '250','state_id' => '13','lga' => 'Ido Osi'),
            array('id' => '251','state_id' => '13','lga' => 'Ijero'),
            array('id' => '252','state_id' => '13','lga' => 'Ikere'),
            array('id' => '253','state_id' => '13','lga' => 'Ikole'),
            array('id' => '254','state_id' => '13','lga' => 'Ilejemeje'),
            array('id' => '255','state_id' => '13','lga' => 'Irepodun/Ifelodun'),
            array('id' => '256','state_id' => '13','lga' => 'Ise/Orun'),
            array('id' => '257','state_id' => '13','lga' => 'Moba'),
            array('id' => '258','state_id' => '13','lga' => 'Oye'),
            array('id' => '259','state_id' => '14','lga' => 'Aninri'),
            array('id' => '260','state_id' => '14','lga' => 'Awgu'),
            array('id' => '261','state_id' => '14','lga' => 'Enugu East'),
            array('id' => '262','state_id' => '14','lga' => 'Enugu North'),
            array('id' => '263','state_id' => '14','lga' => 'Enugu South'),
            array('id' => '264','state_id' => '14','lga' => 'Ezeagu'),
            array('id' => '265','state_id' => '14','lga' => 'Igbo Etiti'),
            array('id' => '266','state_id' => '14','lga' => 'Igbo Eze North'),
            array('id' => '267','state_id' => '14','lga' => 'Igbo Eze South'),
            array('id' => '268','state_id' => '14','lga' => 'Isi Uzo'),
            array('id' => '269','state_id' => '14','lga' => 'Nkanu East'),
            array('id' => '270','state_id' => '14','lga' => 'Nkanu West'),
            array('id' => '271','state_id' => '14','lga' => 'Nsukka'),
            array('id' => '272','state_id' => '14','lga' => 'Oji River'),
            array('id' => '273','state_id' => '14','lga' => 'Udenu'),
            array('id' => '274','state_id' => '14','lga' => 'Udi'),
            array('id' => '275','state_id' => '14','lga' => 'Uzo Uwani'),
            array('id' => '276','state_id' => '15','lga' => 'Abaji'),
            array('id' => '277','state_id' => '15','lga' => 'Bwari'),
            array('id' => '278','state_id' => '15','lga' => 'Gwagwalada'),
            array('id' => '279','state_id' => '15','lga' => 'Kuje'),
            array('id' => '280','state_id' => '15','lga' => 'Kwali'),
            array('id' => '281','state_id' => '15','lga' => 'Municipal Area Council'),
            array('id' => '282','state_id' => '16','lga' => 'Akko'),
            array('id' => '283','state_id' => '16','lga' => 'Balanga'),
            array('id' => '284','state_id' => '16','lga' => 'Billiri'),
            array('id' => '285','state_id' => '16','lga' => 'Dukku'),
            array('id' => '286','state_id' => '16','lga' => 'Funakaye'),
            array('id' => '287','state_id' => '16','lga' => 'Gombe'),
            array('id' => '288','state_id' => '16','lga' => 'Kaltungo'),
            array('id' => '289','state_id' => '16','lga' => 'Kwami'),
            array('id' => '290','state_id' => '16','lga' => 'Nafada'),
            array('id' => '291','state_id' => '16','lga' => 'Shongom'),
            array('id' => '292','state_id' => '16','lga' => 'Yamaltu/Deba'),
            array('id' => '293','state_id' => '17','lga' => 'Aboh Mbaise'),
            array('id' => '294','state_id' => '17','lga' => 'Ahiazu Mbaise'),
            array('id' => '295','state_id' => '17','lga' => 'Ehime Mbano'),
            array('id' => '296','state_id' => '17','lga' => 'Ezinihitte'),
            array('id' => '297','state_id' => '17','lga' => 'Ideato North'),
            array('id' => '298','state_id' => '17','lga' => 'Ideato South'),
            array('id' => '299','state_id' => '17','lga' => 'Ihitte/Uboma'),
            array('id' => '300','state_id' => '17','lga' => 'Ikeduru'),
            array('id' => '301','state_id' => '17','lga' => 'Isiala Mbano'),
            array('id' => '302','state_id' => '17','lga' => 'Isu'),
            array('id' => '303','state_id' => '17','lga' => 'Mbaitoli'),
            array('id' => '304','state_id' => '17','lga' => 'Ngor Okpala'),
            array('id' => '305','state_id' => '17','lga' => 'Njaba'),
            array('id' => '306','state_id' => '17','lga' => 'Nkwerre'),
            array('id' => '307','state_id' => '17','lga' => 'Nwangele'),
            array('id' => '308','state_id' => '17','lga' => 'Obowo'),
            array('id' => '309','state_id' => '17','lga' => 'Oguta'),
            array('id' => '310','state_id' => '17','lga' => 'Ohaji/Egbema'),
            array('id' => '311','state_id' => '17','lga' => 'Okigwe'),
            array('id' => '312','state_id' => '17','lga' => 'Orlu'),
            array('id' => '313','state_id' => '17','lga' => 'Orsu'),
            array('id' => '314','state_id' => '17','lga' => 'Oru East'),
            array('id' => '315','state_id' => '17','lga' => 'Oru West'),
            array('id' => '316','state_id' => '17','lga' => 'Owerri Municipal'),
            array('id' => '317','state_id' => '17','lga' => 'Owerri North'),
            array('id' => '318','state_id' => '17','lga' => 'Owerri West'),
            array('id' => '319','state_id' => '17','lga' => 'Unuimo'),
            array('id' => '320','state_id' => '18','lga' => 'Auyo'),
            array('id' => '321','state_id' => '18','lga' => 'Babura'),
            array('id' => '322','state_id' => '18','lga' => 'Biriniwa'),
            array('id' => '323','state_id' => '18','lga' => 'Birnin Kudu'),
            array('id' => '324','state_id' => '18','lga' => 'Buji'),
            array('id' => '325','state_id' => '18','lga' => 'Dutse'),
            array('id' => '326','state_id' => '18','lga' => 'Gagarawa'),
            array('id' => '327','state_id' => '18','lga' => 'Garki'),
            array('id' => '328','state_id' => '18','lga' => 'Gumel'),
            array('id' => '329','state_id' => '18','lga' => 'Guri'),
            array('id' => '330','state_id' => '18','lga' => 'Gwaram'),
            array('id' => '331','state_id' => '18','lga' => 'Gwiwa'),
            array('id' => '332','state_id' => '18','lga' => 'Hadejia'),
            array('id' => '333','state_id' => '18','lga' => 'Jahun'),
            array('id' => '334','state_id' => '18','lga' => 'Kafin Hausa'),
            array('id' => '335','state_id' => '18','lga' => 'Kazaure'),
            array('id' => '336','state_id' => '18','lga' => 'Kiri Kasama'),
            array('id' => '337','state_id' => '18','lga' => 'Kiyawa'),
            array('id' => '338','state_id' => '18','lga' => 'Kaugama'),
            array('id' => '339','state_id' => '18','lga' => 'Maigatari'),
            array('id' => '340','state_id' => '18','lga' => 'Malam Madori'),
            array('id' => '341','state_id' => '18','lga' => 'Miga'),
            array('id' => '342','state_id' => '18','lga' => 'Ringim'),
            array('id' => '343','state_id' => '18','lga' => 'Roni'),
            array('id' => '344','state_id' => '18','lga' => 'Sule Tankarkar'),
            array('id' => '345','state_id' => '18','lga' => 'Taura'),
            array('id' => '346','state_id' => '18','lga' => 'Yankwashi'),
            array('id' => '347','state_id' => '19','lga' => 'Birnin Gwari'),
            array('id' => '348','state_id' => '19','lga' => 'Chikun'),
            array('id' => '349','state_id' => '19','lga' => 'Giwa'),
            array('id' => '350','state_id' => '19','lga' => 'Igabi'),
            array('id' => '351','state_id' => '19','lga' => 'Ikara'),
            array('id' => '352','state_id' => '19','lga' => 'Jaba'),
            array('id' => '353','state_id' => '19','lga' => 'Jema\'a'),
            array('id' => '354','state_id' => '19','lga' => 'Kachia'),
            array('id' => '355','state_id' => '19','lga' => 'Kaduna North'),
            array('id' => '356','state_id' => '19','lga' => 'Kaduna South'),
            array('id' => '357','state_id' => '19','lga' => 'Kagarko'),
            array('id' => '358','state_id' => '19','lga' => 'Kajuru'),
            array('id' => '359','state_id' => '19','lga' => 'Kaura'),
            array('id' => '360','state_id' => '19','lga' => 'Kauru'),
            array('id' => '361','state_id' => '19','lga' => 'Kubau'),
            array('id' => '362','state_id' => '19','lga' => 'Kudan'),
            array('id' => '363','state_id' => '19','lga' => 'Lere'),
            array('id' => '364','state_id' => '19','lga' => 'Makarfi'),
            array('id' => '365','state_id' => '19','lga' => 'Sabon Gari'),
            array('id' => '366','state_id' => '19','lga' => 'Sanga'),
            array('id' => '367','state_id' => '19','lga' => 'Soba'),
            array('id' => '368','state_id' => '19','lga' => 'Zangon Kataf'),
            array('id' => '369','state_id' => '19','lga' => 'Zaria'),
            array('id' => '370','state_id' => '20','lga' => 'Ajingi'),
            array('id' => '371','state_id' => '20','lga' => 'Albasu'),
            array('id' => '372','state_id' => '20','lga' => 'Bagwai'),
            array('id' => '373','state_id' => '20','lga' => 'Bebeji'),
            array('id' => '374','state_id' => '20','lga' => 'Bichi'),
            array('id' => '375','state_id' => '20','lga' => 'Bunkure'),
            array('id' => '376','state_id' => '20','lga' => 'Dala'),
            array('id' => '377','state_id' => '20','lga' => 'Dambatta'),
            array('id' => '378','state_id' => '20','lga' => 'Dawakin Kudu'),
            array('id' => '379','state_id' => '20','lga' => 'Dawakin Tofa'),
            array('id' => '380','state_id' => '20','lga' => 'Doguwa'),
            array('id' => '381','state_id' => '20','lga' => 'Fagge'),
            array('id' => '382','state_id' => '20','lga' => 'Gabasawa'),
            array('id' => '383','state_id' => '20','lga' => 'Garko'),
            array('id' => '384','state_id' => '20','lga' => 'Garun Mallam'),
            array('id' => '385','state_id' => '20','lga' => 'Gaya'),
            array('id' => '386','state_id' => '20','lga' => 'Gezawa'),
            array('id' => '387','state_id' => '20','lga' => 'Gwale'),
            array('id' => '388','state_id' => '20','lga' => 'Gwarzo'),
            array('id' => '389','state_id' => '20','lga' => 'Kabo'),
            array('id' => '390','state_id' => '20','lga' => 'Kano Municipal'),
            array('id' => '391','state_id' => '20','lga' => 'Karaye'),
            array('id' => '392','state_id' => '20','lga' => 'Kibiya'),
            array('id' => '393','state_id' => '20','lga' => 'Kiru'),
            array('id' => '394','state_id' => '20','lga' => 'Kumbotso'),
            array('id' => '395','state_id' => '20','lga' => 'Kunchi'),
            array('id' => '396','state_id' => '20','lga' => 'Kura'),
            array('id' => '397','state_id' => '20','lga' => 'Madobi'),
            array('id' => '398','state_id' => '20','lga' => 'Makoda'),
            array('id' => '399','state_id' => '20','lga' => 'Minjibir'),
            array('id' => '400','state_id' => '20','lga' => 'Nasarawa'),
            array('id' => '401','state_id' => '20','lga' => 'Rano'),
            array('id' => '402','state_id' => '20','lga' => 'Rimin Gado'),
            array('id' => '403','state_id' => '20','lga' => 'Rogo'),
            array('id' => '404','state_id' => '20','lga' => 'Shanono'),
            array('id' => '405','state_id' => '20','lga' => 'Sumaila'),
            array('id' => '406','state_id' => '20','lga' => 'Takai'),
            array('id' => '407','state_id' => '20','lga' => 'Tarauni'),
            array('id' => '408','state_id' => '20','lga' => 'Tofa'),
            array('id' => '409','state_id' => '20','lga' => 'Tsanyawa'),
            array('id' => '410','state_id' => '20','lga' => 'Tudun Wada'),
            array('id' => '411','state_id' => '20','lga' => 'Ungogo'),
            array('id' => '412','state_id' => '20','lga' => 'Warawa'),
            array('id' => '413','state_id' => '20','lga' => 'Wudil'),
            array('id' => '414','state_id' => '21','lga' => 'Bakori'),
            array('id' => '415','state_id' => '21','lga' => 'Batagarawa'),
            array('id' => '416','state_id' => '21','lga' => 'Batsari'),
            array('id' => '417','state_id' => '21','lga' => 'Baure'),
            array('id' => '418','state_id' => '21','lga' => 'Bindawa'),
            array('id' => '419','state_id' => '21','lga' => 'Charanchi'),
            array('id' => '420','state_id' => '21','lga' => 'Dandume'),
            array('id' => '421','state_id' => '21','lga' => 'Danja'),
            array('id' => '422','state_id' => '21','lga' => 'Dan Musa'),
            array('id' => '423','state_id' => '21','lga' => 'Daura'),
            array('id' => '424','state_id' => '21','lga' => 'Dutsi'),
            array('id' => '425','state_id' => '21','lga' => 'Dutsin Ma'),
            array('id' => '426','state_id' => '21','lga' => 'Faskari'),
            array('id' => '427','state_id' => '21','lga' => 'Funtua'),
            array('id' => '428','state_id' => '21','lga' => 'Ingawa'),
            array('id' => '429','state_id' => '21','lga' => 'Jibia'),
            array('id' => '430','state_id' => '21','lga' => 'Kafur'),
            array('id' => '431','state_id' => '21','lga' => 'Kaita'),
            array('id' => '432','state_id' => '21','lga' => 'Kankara'),
            array('id' => '433','state_id' => '21','lga' => 'Kankia'),
            array('id' => '434','state_id' => '21','lga' => 'Katsina'),
            array('id' => '435','state_id' => '21','lga' => 'Kurfi'),
            array('id' => '436','state_id' => '21','lga' => 'Kusada'),
            array('id' => '437','state_id' => '21','lga' => 'Mai\'Adua'),
            array('id' => '438','state_id' => '21','lga' => 'Malumfashi'),
            array('id' => '439','state_id' => '21','lga' => 'Mani'),
            array('id' => '440','state_id' => '21','lga' => 'Mashi'),
            array('id' => '441','state_id' => '21','lga' => 'Matazu'),
            array('id' => '442','state_id' => '21','lga' => 'Musawa'),
            array('id' => '443','state_id' => '21','lga' => 'Rimi'),
            array('id' => '444','state_id' => '21','lga' => 'Sabuwa'),
            array('id' => '445','state_id' => '21','lga' => 'Safana'),
            array('id' => '446','state_id' => '21','lga' => 'Sandamu'),
            array('id' => '447','state_id' => '21','lga' => 'Zango'),
            array('id' => '448','state_id' => '22','lga' => 'Aleiro'),
            array('id' => '449','state_id' => '22','lga' => 'Arewa Dandi'),
            array('id' => '450','state_id' => '22','lga' => 'Argungu'),
            array('id' => '451','state_id' => '22','lga' => 'Augie'),
            array('id' => '452','state_id' => '22','lga' => 'Bagudo'),
            array('id' => '453','state_id' => '22','lga' => 'Birnin Kebbi'),
            array('id' => '454','state_id' => '22','lga' => 'Bunza'),
            array('id' => '455','state_id' => '22','lga' => 'Dandi'),
            array('id' => '456','state_id' => '22','lga' => 'Fakai'),
            array('id' => '457','state_id' => '22','lga' => 'Gwandu'),
            array('id' => '458','state_id' => '22','lga' => 'Jega'),
            array('id' => '459','state_id' => '22','lga' => 'Kalgo'),
            array('id' => '460','state_id' => '22','lga' => 'Koko/Besse'),
            array('id' => '461','state_id' => '22','lga' => 'Maiyama'),
            array('id' => '462','state_id' => '22','lga' => 'Ngaski'),
            array('id' => '463','state_id' => '22','lga' => 'Sakaba'),
            array('id' => '464','state_id' => '22','lga' => 'Shanga'),
            array('id' => '465','state_id' => '22','lga' => 'Suru'),
            array('id' => '466','state_id' => '22','lga' => 'Wasagu/Danko'),
            array('id' => '467','state_id' => '22','lga' => 'Yauri'),
            array('id' => '468','state_id' => '22','lga' => 'Zuru'),
            array('id' => '469','state_id' => '23','lga' => 'Adavi'),
            array('id' => '470','state_id' => '23','lga' => 'Ajaokuta'),
            array('id' => '471','state_id' => '23','lga' => 'Ankpa'),
            array('id' => '472','state_id' => '23','lga' => 'Bassa'),
            array('id' => '473','state_id' => '23','lga' => 'Dekina'),
            array('id' => '474','state_id' => '23','lga' => 'Ibaji'),
            array('id' => '475','state_id' => '23','lga' => 'Idah'),
            array('id' => '476','state_id' => '23','lga' => 'Igalamela Odolu'),
            array('id' => '477','state_id' => '23','lga' => 'Ijumu'),
            array('id' => '478','state_id' => '23','lga' => 'Kabba/Bunu'),
            array('id' => '479','state_id' => '23','lga' => 'Kogi'),
            array('id' => '480','state_id' => '23','lga' => 'Lokoja'),
            array('id' => '481','state_id' => '23','lga' => 'Mopa Muro'),
            array('id' => '482','state_id' => '23','lga' => 'Ofu'),
            array('id' => '483','state_id' => '23','lga' => 'Ogori/Magongo'),
            array('id' => '484','state_id' => '23','lga' => 'Okehi'),
            array('id' => '485','state_id' => '23','lga' => 'Okene'),
            array('id' => '486','state_id' => '23','lga' => 'Olamaboro'),
            array('id' => '487','state_id' => '23','lga' => 'Omala'),
            array('id' => '488','state_id' => '23','lga' => 'Yagba East'),
            array('id' => '489','state_id' => '23','lga' => 'Yagba West'),
            array('id' => '490','state_id' => '24','lga' => 'Asa'),
            array('id' => '491','state_id' => '24','lga' => 'Baruten'),
            array('id' => '492','state_id' => '24','lga' => 'Edu'),
            array('id' => '493','state_id' => '24','lga' => 'Ekiti, Kwara State'),
            array('id' => '494','state_id' => '24','lga' => 'Ifelodun'),
            array('id' => '495','state_id' => '24','lga' => 'Ilorin East'),
            array('id' => '496','state_id' => '24','lga' => 'Ilorin South'),
            array('id' => '497','state_id' => '24','lga' => 'Ilorin West'),
            array('id' => '498','state_id' => '24','lga' => 'Irepodun'),
            array('id' => '499','state_id' => '24','lga' => 'Isin'),
            array('id' => '500','state_id' => '24','lga' => 'Kaiama'),
            array('id' => '501','state_id' => '24','lga' => 'Moro'),
            array('id' => '502','state_id' => '24','lga' => 'Offa'),
            array('id' => '503','state_id' => '24','lga' => 'Oke Ero'),
            array('id' => '504','state_id' => '24','lga' => 'Oyun'),
            array('id' => '505','state_id' => '24','lga' => 'Pategi'),
            array('id' => '506','state_id' => '25','lga' => 'Agege'),
            array('id' => '507','state_id' => '25','lga' => 'Ajeromi-Ifelodun'),
            array('id' => '508','state_id' => '25','lga' => 'Alimosho'),
            array('id' => '509','state_id' => '25','lga' => 'Amuwo-Odofin'),
            array('id' => '510','state_id' => '25','lga' => 'Apapa'),
            array('id' => '511','state_id' => '25','lga' => 'Badagry'),
            array('id' => '512','state_id' => '25','lga' => 'Epe'),
            array('id' => '513','state_id' => '25','lga' => 'Eti Osa'),
            array('id' => '514','state_id' => '25','lga' => 'Ibeju-Lekki'),
            array('id' => '515','state_id' => '25','lga' => 'Ifako-Ijaiye'),
            array('id' => '516','state_id' => '25','lga' => 'Ikeja'),
            array('id' => '517','state_id' => '25','lga' => 'Ikorodu'),
            array('id' => '518','state_id' => '25','lga' => 'Kosofe'),
            array('id' => '519','state_id' => '25','lga' => 'Lagos Island'),
            array('id' => '520','state_id' => '25','lga' => 'Lagos Mainland'),
            array('id' => '521','state_id' => '25','lga' => 'Mushin'),
            array('id' => '522','state_id' => '25','lga' => 'Ojo'),
            array('id' => '523','state_id' => '25','lga' => 'Oshodi-Isolo'),
            array('id' => '524','state_id' => '25','lga' => 'Shomolu'),
            array('id' => '525','state_id' => '25','lga' => 'Surulere, Lagos State'),
            array('id' => '526','state_id' => '26','lga' => 'Akwanga'),
            array('id' => '527','state_id' => '26','lga' => 'Awe'),
            array('id' => '528','state_id' => '26','lga' => 'Doma'),
            array('id' => '529','state_id' => '26','lga' => 'Karu'),
            array('id' => '530','state_id' => '26','lga' => 'Keana'),
            array('id' => '531','state_id' => '26','lga' => 'Keffi'),
            array('id' => '532','state_id' => '26','lga' => 'Kokona'),
            array('id' => '533','state_id' => '26','lga' => 'Lafia'),
            array('id' => '534','state_id' => '26','lga' => 'Nasarawa'),
            array('id' => '535','state_id' => '26','lga' => 'Nasarawa Egon'),
            array('id' => '536','state_id' => '26','lga' => 'Obi'),
            array('id' => '537','state_id' => '26','lga' => 'Toto'),
            array('id' => '538','state_id' => '26','lga' => 'Wamba'),
            array('id' => '539','state_id' => '27','lga' => 'Agaie'),
            array('id' => '540','state_id' => '27','lga' => 'Agwara'),
            array('id' => '541','state_id' => '27','lga' => 'Bida'),
            array('id' => '542','state_id' => '27','lga' => 'Borgu'),
            array('id' => '543','state_id' => '27','lga' => 'Bosso'),
            array('id' => '544','state_id' => '27','lga' => 'Chanchaga'),
            array('id' => '545','state_id' => '27','lga' => 'Edati'),
            array('id' => '546','state_id' => '27','lga' => 'Gbako'),
            array('id' => '547','state_id' => '27','lga' => 'Gurara'),
            array('id' => '548','state_id' => '27','lga' => 'Katcha'),
            array('id' => '549','state_id' => '27','lga' => 'Kontagora'),
            array('id' => '550','state_id' => '27','lga' => 'Lapai'),
            array('id' => '551','state_id' => '27','lga' => 'Lavun'),
            array('id' => '552','state_id' => '27','lga' => 'Magama'),
            array('id' => '553','state_id' => '27','lga' => 'Mariga'),
            array('id' => '554','state_id' => '27','lga' => 'Mashegu'),
            array('id' => '555','state_id' => '27','lga' => 'Mokwa'),
            array('id' => '556','state_id' => '27','lga' => 'Moya'),
            array('id' => '557','state_id' => '27','lga' => 'Paikoro'),
            array('id' => '558','state_id' => '27','lga' => 'Rafi'),
            array('id' => '559','state_id' => '27','lga' => 'Rijau'),
            array('id' => '560','state_id' => '27','lga' => 'Shiroro'),
            array('id' => '561','state_id' => '27','lga' => 'Suleja'),
            array('id' => '562','state_id' => '27','lga' => 'Tafa'),
            array('id' => '563','state_id' => '27','lga' => 'Wushishi'),
            array('id' => '564','state_id' => '28','lga' => 'Abeokuta North'),
            array('id' => '565','state_id' => '28','lga' => 'Abeokuta South'),
            array('id' => '566','state_id' => '28','lga' => 'Ado-Odo/Ota'),
            array('id' => '567','state_id' => '28','lga' => 'Egbado North'),
            array('id' => '568','state_id' => '28','lga' => 'Egbado South'),
            array('id' => '569','state_id' => '28','lga' => 'Ewekoro'),
            array('id' => '570','state_id' => '28','lga' => 'Ifo'),
            array('id' => '571','state_id' => '28','lga' => 'Ijebu East'),
            array('id' => '572','state_id' => '28','lga' => 'Ijebu North'),
            array('id' => '573','state_id' => '28','lga' => 'Ijebu North East'),
            array('id' => '574','state_id' => '28','lga' => 'Ijebu Ode'),
            array('id' => '575','state_id' => '28','lga' => 'Ikenne'),
            array('id' => '576','state_id' => '28','lga' => 'Imeko Afon'),
            array('id' => '577','state_id' => '28','lga' => 'Ipokia'),
            array('id' => '578','state_id' => '28','lga' => 'Obafemi Owode'),
            array('id' => '579','state_id' => '28','lga' => 'Odeda'),
            array('id' => '580','state_id' => '28','lga' => 'Odogbolu'),
            array('id' => '581','state_id' => '28','lga' => 'Ogun Waterside'),
            array('id' => '582','state_id' => '28','lga' => 'Remo North'),
            array('id' => '583','state_id' => '28','lga' => 'Shagamu'),
            array('id' => '584','state_id' => '29','lga' => 'Akoko North-East'),
            array('id' => '585','state_id' => '29','lga' => 'Akoko North-West'),
            array('id' => '586','state_id' => '29','lga' => 'Akoko South-West'),
            array('id' => '587','state_id' => '29','lga' => 'Akoko South-East'),
            array('id' => '588','state_id' => '29','lga' => 'Akure North'),
            array('id' => '589','state_id' => '29','lga' => 'Akure South'),
            array('id' => '590','state_id' => '29','lga' => 'Ese Odo'),
            array('id' => '591','state_id' => '29','lga' => 'Idanre'),
            array('id' => '592','state_id' => '29','lga' => 'Ifedore'),
            array('id' => '593','state_id' => '29','lga' => 'Ilaje'),
            array('id' => '594','state_id' => '29','lga' => 'Ile Oluji/Okeigbo'),
            array('id' => '595','state_id' => '29','lga' => 'Irele'),
            array('id' => '596','state_id' => '29','lga' => 'Odigbo'),
            array('id' => '597','state_id' => '29','lga' => 'Okitipupa'),
            array('id' => '598','state_id' => '29','lga' => 'Ondo East'),
            array('id' => '599','state_id' => '29','lga' => 'Ondo West'),
            array('id' => '600','state_id' => '29','lga' => 'Ose'),
            array('id' => '601','state_id' => '29','lga' => 'Owo'),
            array('id' => '602','state_id' => '30','lga' => 'Atakunmosa East'),
            array('id' => '603','state_id' => '30','lga' => 'Atakunmosa West'),
            array('id' => '604','state_id' => '30','lga' => 'Aiyedaade'),
            array('id' => '605','state_id' => '30','lga' => 'Aiyedire'),
            array('id' => '606','state_id' => '30','lga' => 'Boluwaduro'),
            array('id' => '607','state_id' => '30','lga' => 'Boripe'),
            array('id' => '608','state_id' => '30','lga' => 'Ede North'),
            array('id' => '609','state_id' => '30','lga' => 'Ede South'),
            array('id' => '610','state_id' => '30','lga' => 'Ife Central'),
            array('id' => '611','state_id' => '30','lga' => 'Ife East'),
            array('id' => '612','state_id' => '30','lga' => 'Ife North'),
            array('id' => '613','state_id' => '30','lga' => 'Ife South'),
            array('id' => '614','state_id' => '30','lga' => 'Egbedore'),
            array('id' => '615','state_id' => '30','lga' => 'Ejigbo'),
            array('id' => '616','state_id' => '30','lga' => 'Ifedayo'),
            array('id' => '617','state_id' => '30','lga' => 'Ifelodun'),
            array('id' => '618','state_id' => '30','lga' => 'Ila'),
            array('id' => '619','state_id' => '30','lga' => 'Ilesa East'),
            array('id' => '620','state_id' => '30','lga' => 'Ilesa West'),
            array('id' => '621','state_id' => '30','lga' => 'Irepodun'),
            array('id' => '622','state_id' => '30','lga' => 'Irewole'),
            array('id' => '623','state_id' => '30','lga' => 'Isokan'),
            array('id' => '624','state_id' => '30','lga' => 'Iwo'),
            array('id' => '625','state_id' => '30','lga' => 'Obokun'),
            array('id' => '626','state_id' => '30','lga' => 'Odo Otin'),
            array('id' => '627','state_id' => '30','lga' => 'Ola Oluwa'),
            array('id' => '628','state_id' => '30','lga' => 'Olorunda'),
            array('id' => '629','state_id' => '30','lga' => 'Oriade'),
            array('id' => '630','state_id' => '30','lga' => 'Orolu'),
            array('id' => '631','state_id' => '30','lga' => 'Osogbo'),
            array('id' => '632','state_id' => '31','lga' => 'Afijio'),
            array('id' => '633','state_id' => '31','lga' => 'Akinyele'),
            array('id' => '634','state_id' => '31','lga' => 'Atiba'),
            array('id' => '635','state_id' => '31','lga' => 'Atisbo'),
            array('id' => '636','state_id' => '31','lga' => 'Egbeda'),
            array('id' => '637','state_id' => '31','lga' => 'Ibadan North'),
            array('id' => '638','state_id' => '31','lga' => 'Ibadan North-East'),
            array('id' => '639','state_id' => '31','lga' => 'Ibadan North-West'),
            array('id' => '640','state_id' => '31','lga' => 'Ibadan South-East'),
            array('id' => '641','state_id' => '31','lga' => 'Ibadan South-West'),
            array('id' => '642','state_id' => '31','lga' => 'Ibarapa Central'),
            array('id' => '643','state_id' => '31','lga' => 'Ibarapa East'),
            array('id' => '644','state_id' => '31','lga' => 'Ibarapa North'),
            array('id' => '645','state_id' => '31','lga' => 'Ido'),
            array('id' => '646','state_id' => '31','lga' => 'Irepo'),
            array('id' => '647','state_id' => '31','lga' => 'Iseyin'),
            array('id' => '648','state_id' => '31','lga' => 'Itesiwaju'),
            array('id' => '649','state_id' => '31','lga' => 'Iwajowa'),
            array('id' => '650','state_id' => '31','lga' => 'Kajola'),
            array('id' => '651','state_id' => '31','lga' => 'Lagelu'),
            array('id' => '652','state_id' => '31','lga' => 'Ogbomosho North'),
            array('id' => '653','state_id' => '31','lga' => 'Ogbomosho South'),
            array('id' => '654','state_id' => '31','lga' => 'Ogo Oluwa'),
            array('id' => '655','state_id' => '31','lga' => 'Olorunsogo'),
            array('id' => '656','state_id' => '31','lga' => 'Oluyole'),
            array('id' => '657','state_id' => '31','lga' => 'Ona Ara'),
            array('id' => '658','state_id' => '31','lga' => 'Orelope'),
            array('id' => '659','state_id' => '31','lga' => 'Ori Ire'),
            array('id' => '660','state_id' => '31','lga' => 'Oyo'),
            array('id' => '661','state_id' => '31','lga' => 'Oyo East'),
            array('id' => '662','state_id' => '31','lga' => 'Saki East'),
            array('id' => '663','state_id' => '31','lga' => 'Saki West'),
            array('id' => '664','state_id' => '31','lga' => 'Surulere, Oyo State'),
            array('id' => '665','state_id' => '32','lga' => 'Bokkos'),
            array('id' => '666','state_id' => '32','lga' => 'Barkin Ladi'),
            array('id' => '667','state_id' => '32','lga' => 'Bassa'),
            array('id' => '668','state_id' => '32','lga' => 'Jos East'),
            array('id' => '669','state_id' => '32','lga' => 'Jos North'),
            array('id' => '670','state_id' => '32','lga' => 'Jos South'),
            array('id' => '671','state_id' => '32','lga' => 'Kanam'),
            array('id' => '672','state_id' => '32','lga' => 'Kanke'),
            array('id' => '673','state_id' => '32','lga' => 'Langtang South'),
            array('id' => '674','state_id' => '32','lga' => 'Langtang North'),
            array('id' => '675','state_id' => '32','lga' => 'Mangu'),
            array('id' => '676','state_id' => '32','lga' => 'Mikang'),
            array('id' => '677','state_id' => '32','lga' => 'Pankshin'),
            array('id' => '678','state_id' => '32','lga' => 'Qua\'an Pan'),
            array('id' => '679','state_id' => '32','lga' => 'Riyom'),
            array('id' => '680','state_id' => '32','lga' => 'Shendam'),
            array('id' => '681','state_id' => '32','lga' => 'Wase'),
            array('id' => '682','state_id' => '33','lga' => 'Abua/Odual'),
            array('id' => '683','state_id' => '33','lga' => 'Ahoada East'),
            array('id' => '684','state_id' => '33','lga' => 'Ahoada West'),
            array('id' => '685','state_id' => '33','lga' => 'Akuku-Toru'),
            array('id' => '686','state_id' => '33','lga' => 'Andoni'),
            array('id' => '687','state_id' => '33','lga' => 'Asari-Toru'),
            array('id' => '688','state_id' => '33','lga' => 'Bonny'),
            array('id' => '689','state_id' => '33','lga' => 'Degema'),
            array('id' => '690','state_id' => '33','lga' => 'Eleme'),
            array('id' => '691','state_id' => '33','lga' => 'Emuoha'),
            array('id' => '692','state_id' => '33','lga' => 'Etche'),
            array('id' => '693','state_id' => '33','lga' => 'Gokana'),
            array('id' => '694','state_id' => '33','lga' => 'Ikwerre'),
            array('id' => '695','state_id' => '33','lga' => 'Khana'),
            array('id' => '696','state_id' => '33','lga' => 'Obio/Akpor'),
            array('id' => '697','state_id' => '33','lga' => 'Ogba/Egbema/Ndoni'),
            array('id' => '698','state_id' => '33','lga' => 'Ogu/Bolo'),
            array('id' => '699','state_id' => '33','lga' => 'Okrika'),
            array('id' => '700','state_id' => '33','lga' => 'Omuma'),
            array('id' => '701','state_id' => '33','lga' => 'Opobo/Nkoro'),
            array('id' => '702','state_id' => '33','lga' => 'Oyigbo'),
            array('id' => '703','state_id' => '33','lga' => 'Port Harcourt'),
            array('id' => '704','state_id' => '33','lga' => 'Tai'),
            array('id' => '705','state_id' => '34','lga' => 'Binji'),
            array('id' => '706','state_id' => '34','lga' => 'Bodinga'),
            array('id' => '707','state_id' => '34','lga' => 'Dange Shuni'),
            array('id' => '708','state_id' => '34','lga' => 'Gada'),
            array('id' => '709','state_id' => '34','lga' => 'Goronyo'),
            array('id' => '710','state_id' => '34','lga' => 'Gudu'),
            array('id' => '711','state_id' => '34','lga' => 'Gwadabawa'),
            array('id' => '712','state_id' => '34','lga' => 'Illela'),
            array('id' => '713','state_id' => '34','lga' => 'Isa'),
            array('id' => '714','state_id' => '34','lga' => 'Kebbe'),
            array('id' => '715','state_id' => '34','lga' => 'Kware'),
            array('id' => '716','state_id' => '34','lga' => 'Rabah'),
            array('id' => '717','state_id' => '34','lga' => 'Sabon Birni'),
            array('id' => '718','state_id' => '34','lga' => 'Shagari'),
            array('id' => '719','state_id' => '34','lga' => 'Silame'),
            array('id' => '720','state_id' => '34','lga' => 'Sokoto North'),
            array('id' => '721','state_id' => '34','lga' => 'Sokoto South'),
            array('id' => '722','state_id' => '34','lga' => 'Tambuwal'),
            array('id' => '723','state_id' => '34','lga' => 'Tangaza'),
            array('id' => '724','state_id' => '34','lga' => 'Tureta'),
            array('id' => '725','state_id' => '34','lga' => 'Wamako'),
            array('id' => '726','state_id' => '34','lga' => 'Wurno'),
            array('id' => '727','state_id' => '34','lga' => 'Yabo'),
            array('id' => '728','state_id' => '35','lga' => 'Ardo Kola'),
            array('id' => '729','state_id' => '35','lga' => 'Bali'),
            array('id' => '730','state_id' => '35','lga' => 'Donga'),
            array('id' => '731','state_id' => '35','lga' => 'Gashaka'),
            array('id' => '732','state_id' => '35','lga' => 'Gassol'),
            array('id' => '733','state_id' => '35','lga' => 'Ibi'),
            array('id' => '734','state_id' => '35','lga' => 'Jalingo'),
            array('id' => '735','state_id' => '35','lga' => 'Karim Lamido'),
            array('id' => '736','state_id' => '35','lga' => 'Kumi'),
            array('id' => '737','state_id' => '35','lga' => 'Lau'),
            array('id' => '738','state_id' => '35','lga' => 'Sardauna'),
            array('id' => '739','state_id' => '35','lga' => 'Takum'),
            array('id' => '740','state_id' => '35','lga' => 'Ussa'),
            array('id' => '741','state_id' => '35','lga' => 'Wukari'),
            array('id' => '742','state_id' => '35','lga' => 'Yorro'),
            array('id' => '743','state_id' => '35','lga' => 'Zing'),
            array('id' => '744','state_id' => '36','lga' => 'Bade'),
            array('id' => '745','state_id' => '36','lga' => 'Bursari'),
            array('id' => '746','state_id' => '36','lga' => 'Damaturu'),
            array('id' => '747','state_id' => '36','lga' => 'Fika'),
            array('id' => '748','state_id' => '36','lga' => 'Fune'),
            array('id' => '749','state_id' => '36','lga' => 'Geidam'),
            array('id' => '750','state_id' => '36','lga' => 'Gujba'),
            array('id' => '751','state_id' => '36','lga' => 'Gulani'),
            array('id' => '752','state_id' => '36','lga' => 'Jakusko'),
            array('id' => '753','state_id' => '36','lga' => 'Karasuwa'),
            array('id' => '754','state_id' => '36','lga' => 'Machina'),
            array('id' => '755','state_id' => '36','lga' => 'Nangere'),
            array('id' => '756','state_id' => '36','lga' => 'Nguru'),
            array('id' => '757','state_id' => '36','lga' => 'Potiskum'),
            array('id' => '758','state_id' => '36','lga' => 'Tarmuwa'),
            array('id' => '759','state_id' => '36','lga' => 'Yunusari'),
            array('id' => '760','state_id' => '36','lga' => 'Yusufari'),
            array('id' => '761','state_id' => '37','lga' => 'Anka'),
            array('id' => '762','state_id' => '37','lga' => 'Bakura'),
            array('id' => '763','state_id' => '37','lga' => 'Birnin Magaji/Kiyaw'),
            array('id' => '764','state_id' => '37','lga' => 'Bukkuyum'),
            array('id' => '765','state_id' => '37','lga' => 'Bungudu'),
            array('id' => '766','state_id' => '37','lga' => 'Gummi'),
            array('id' => '767','state_id' => '37','lga' => 'Gusau'),
            array('id' => '768','state_id' => '37','lga' => 'Kaura Namoda'),
            array('id' => '769','state_id' => '37','lga' => 'Maradun'),
            array('id' => '770','state_id' => '37','lga' => 'Maru'),
            array('id' => '771','state_id' => '37','lga' => 'Shinkafi'),
            array('id' => '772','state_id' => '37','lga' => 'Talata Mafara'),
            array('id' => '773','state_id' => '37','lga' => 'Chafe'),
            array('id' => '774','state_id' => '37','lga' => 'Zurmi')
        );
        foreach ($locations as $key => $value) {
            $location = new Location();
            $location->state_id = $value['state_id'];
            $location->lga = $value['lga'];
            $location->save();
        }
    }
}
